### ISSUE TITLE
collapsing of 0 values

### ISSUE THREAD

**Issue by SEAPUNK** [jamen/css-collapse-values#1]
`0em === 0px === 0rem === 0 === 0etc`

**Comment by SEAPUNK** [comment]
also,

`04px === 4px`

**Comment by jamen** [comment]
Good point.  I wanted to avoid any type conversion or checking at first, but I guess it would make sense for `0`.

**Comment by SEAPUNK** [comment]
you can't really convert types with css without knowing the full context

**Comment by jamen** [comment]
Right, but things like `em` or `rem` can be assumed `16` or supplied through options, was the idea we had in chat.  But I ultimately didn't like it which is why it isn't added.

**Comment by SEAPUNK** [comment]
> Right, but things like em or rem can be assumed 16px

nope, it can vary by browser, or user settings

besides, if you're going to do type conversions, it's best that it's done in its own module, and in this module, have an option called 'convertTypes' or something

**Comment by jamen** [comment]
fair enough.  pretty much the reason I didn't add it, and the initial idea called for a `convert` option.
